/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaInvalidObjectException : JavaObjectStreamException {

  private static let serialVersionUID:jlong = 3233174318281839583


  public override init(_ detailMessage:String?)  {
    
    super.init(detailMessage)
  }


}
