/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaObjectStreamException : JavaIOException {

  private static let serialVersionUID:jlong = 7260898174833392607


  override init()  {
    
    super.init()
  }

  override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
