/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public protocol JavaAppendable  {
  func append(c:jchar) throws ->JavaAppendable?
  func append(csq:JavaCharSequence?) throws ->JavaAppendable?
  func append(csq:JavaCharSequence?, _ start:jint, _ end:jint) throws ->JavaAppendable?

}
