/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaArithmeticException : JavaRuntimeException {

  private static let serialVersionUID:jlong = 2256477558314496007


  public override init()  {
    
    super.init()
  }

  public override init(_ detailMessage:String?)  {
    
    super.init(detailMessage)
  }


}
