/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaArrayIndexOutOfBoundsException : JavaIndexOutOfBoundsException {

  private static let serialVersionUID:jlong = -5116101128118950844


  public override init()  {
    
    super.init()
  }

  public init(_ index:jint)  {
    
    super.init("index=\(index)")
  }

  public override init(_ detailMessage:String?)  {
    
    super.init(detailMessage)
  }

  public init(_ sourceLength:jint, _ index:jint)  {
    
    super.init("length=\(sourceLength); index=\(index)")
  }

  public init(_ sourceLength:jint, _ offset:jint, _ count:jint)  {
    
    super.init("length=\(sourceLength); regionStart=\(offset); regionLength=\(count)")
  }


}
