/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaArrayStoreException : JavaRuntimeException {
  private static let serialVersionUID:jlong = -4522193890499838241


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
