/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaArrayIndexOutOfBoundsException : JavaIndexOutOfBoundsException {
  private static let serialVersionUID:jlong = -5116101128118950844


  public override init()  {
    
    super.init()
  }

  public init(withjint index:jint)  {
    
    super.init(withString: "index=\(index)")
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }

  public init(withjint sourceLength:jint, withjint index:jint)  {
    
    super.init(withString: "length=\(sourceLength); index=\(index)")
  }

  public init(withjint sourceLength:jint, withjint offset:jint, withjint count:jint)  {
    
    super.init(withString: "length=\(sourceLength); regionStart=\(offset); regionLength=\(count)")
  }


}
