/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaAssertionError : JavaError {

  private static let serialVersionUID:jlong = -5013299493970297370


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?, withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: detailMessage,withJavaThrowable: cause)
  }

  public init(withJavaObject detailMessage:JavaObject?)  {
    
    super.init(withString: String.valueOf(detailMessage))
    if (detailMessage is JavaThrowable) {
      initCause((detailMessage as! JavaThrowable))
    }
  }

//  public convenience init(withjboolean detailMessage:jboolean)  {
//    self.init(String.valueOf(detailMessage))
//  }
//
//  public convenience init(withjchar detailMessage:jchar)  {
//    self.init(String.valueOf(detailMessage))
//  }
//
//  public convenience init(withjint detailMessage:jint)  {
//    self.init(JavaInteger.toString(detailMessage))
//  }
//
//  public convenience init(withjlong detailMessage:jlong)  {
//    self.init(JavaLong.toString(detailMessage))
//  }
//
//  public convenience init(withjfloat detailMessage:jfloat)  {
//    self.init(JavaFloat.toString(detailMessage))
//  }
//
//  public convenience init(withjdouble detailMessage:jdouble)  {
//    self.init(JavaDouble.toString(detailMessage))
//  }


}
