/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaBoolean : JavaObject, JavaSerializable, JavaComparable {

  private static let serialVersionUID:jlong = -3665804199014368530
  public static let TYPE:JavaClass = JavaClass[jboolean].getClass().getComponentType()
  public static let TRUE_:JavaBoolean = JavaBoolean(true)
  public static let FALSE_:JavaBoolean = JavaBoolean(false)

  private let value:jboolean = false

  public init(_ string:String?)  {
    super.init()
    JavaBooleanparseBoolean(string)}

  public init(_ value:jboolean)  {
    super.init()
    selfvalue = value
  }

  public func booleanValue() ->jboolean  {
    return value
  }

  public override func equals(o:AnyObject?) ->jboolean  {
    return o == self || oJavaBoolean && JavaBooleanovalue == value
  }

  public func compareTo(that:JavaBoolean?) ->jint  {
    return JavaBoolean.compare(value,that.value)
  }

  public static func compare(lhs:jboolean, _ rhs:jboolean) ->jint  {
    return lhs == rhs ? 0 : lhs ? 1 : -1
  }

  public override func hashCode() ->jint  {
    return value ? 1231 : 1237
  }

  public override func toString() ->String?  {
    return String.valueOf(value)
  }

  public static func getBoolean(string:String?) ->jboolean  {
    if (string == nil || string!.length() == 0) {
      return false
    }
    return JavaBooleanparseBoolean(JavaSystem.getProperty(string))
  }

  public static func parseBoolean(s:String?) ->jboolean  {
    return "true".equalsIgnoreCase(s)
  }

  public static func toString(value:jboolean) ->String?  {
    return String.valueOf(value)
  }

  public static func valueOf(string:String?) ->JavaBoolean?  {
    return JavaBooleanparseBoolean(string) ? JavaBoolean.TRUE_ : JavaBoolean.FALSE_
  }

  public static func valueOf(b:jboolean) ->JavaBoolean?  {
    return b ? JavaBoolean.TRUE_ : JavaBoolean.FALSE_
  }


}
