/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public protocol JavaCharSequence  {
  func length() ->jint
  func charAt(index:jint) ->jchar
  func subSequence(start:jint, _ end:jint) ->JavaCharSequence?
  func toString() ->String?

}
