/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaClassCastException : JavaRuntimeException {

  private static let serialVersionUID:jlong = -9223365651070458532


  public override init()  {
    
    super.init()
  }

  public override init(_ detailMessage:String?)  {
    
    super.init(detailMessage)
  }


}
