/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaException : JavaThrowable {
  private static let serialVersionUID:jlong = -3387516993124229948


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }

  public override init(withString detailMessage:String?, withJavaThrowable throwable:JavaThrowable?)  {
    
    super.init(withString: detailMessage,withJavaThrowable: throwable)
  }

  public override init(withJavaThrowable throwable:JavaThrowable?)  {
    
    super.init(withJavaThrowable: throwable)
  }

  override init(withString message:String?, withJavaThrowable cause:JavaThrowable?, withjboolean enableSuppression:jboolean, withjboolean writableStackTrace:jboolean)  {
    
    super.init(withString: message,withJavaThrowable: cause,withjboolean: enableSuppression,withjboolean: writableStackTrace)
  }


}
