/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaIllegalArgumentException : JavaRuntimeException {

  private static let serialVersionUID:jlong = -5365630128856068164


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }

  public override init(withString message:String?, withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: message,withJavaThrowable: cause)
  }

  public override init(withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: cause == nil ? nil : cause!.toString(),withJavaThrowable: cause)
  }


}
