/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaIndexOutOfBoundsException : JavaRuntimeException {
  private static let serialVersionUID:jlong = 234122996006267687


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
