/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaNegativeArraySizeException : JavaRuntimeException {
  private static let serialVersionUID:jlong = -8960118058596991861


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
