/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaNoSuchFieldException : JavaReflectiveOperationException {
  private static let serialVersionUID:jlong = -6143714805279938260


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
