/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaNullPointerException : JavaRuntimeException {
  private static let serialVersionUID:jlong = 5162710183389028792


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
