/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaNumberFormatException : JavaIllegalArgumentException {

  private static let serialVersionUID:jlong = -2848938806368998894


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }


}
