/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaNumber : JavaObject, JavaSerializable {

  private static let serialVersionUID:jlong = -8742448824652078965


  public func byteValue() ->jbyte  {
    return (intValue() as jbyte?)
  }

  public func shortValue() ->jshort  {
    return (intValue() as jshort?)
  }


}
