/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaReflectiveOperationException : JavaException {


  public override init()  {
    
    super.init()
  }

  public override init(_ message:String?)  {
    
    super.init(message)
  }

  public override init(_ cause:JavaThrowable?)  {
    
    super.init(cause)
  }

  public override init(_ message:String?, _ cause:JavaThrowable?)  {
    
    super.init(message,cause)
  }


}
