/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaReflectiveOperationException : JavaException {


  public override init()  {
    
    super.init()
  }

  public override init(withString message:String?)  {
    
    super.init(withString: message)
  }

  public override init(withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withJavaThrowable: cause)
  }

  public override init(withString message:String?, withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: message,withJavaThrowable: cause)
  }


}
