/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaSecurityException : JavaRuntimeException {
  private static let serialVersionUID:jlong = 6878364983674394167


  public override init()  {
    
    super.init()
  }

  public override init(withString detailMessage:String?)  {
    
    super.init(withString: detailMessage)
  }

  public override init(withString message:String?, withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: message,withJavaThrowable: cause)
  }

  public override init(withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: cause == nil ? nil : cause!.toString(),withJavaThrowable: cause)
  }


}
