/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaStringIndexOutOfBoundsException : JavaIndexOutOfBoundsException {

  private static let serialVersionUID:jlong = -6762910422159637258


  public override init()  {
    
    super.init()
  }

  public init(_ index:jint)  {
    
    super.init("String index out of range: \(index)")
  }

  public override init(_ detailMessage:String?)  {
    
    super.init(detailMessage)
  }

  public convenience init(_ s:String?, _ index:jint)  {
    self.init(s!.length(),index)
  }

  public init(_ sourceLength:jint, _ index:jint)  {
    
    super.init("length=\(sourceLength); index=\(index)")
  }

  public convenience init(_ s:String?, _ offset:jint, _ count:jint)  {
    self.init(s!.length(),offset,count)
  }

  public init(_ sourceLength:jint, _ offset:jint, _ count:jint)  {
    
    super.init("length=\(sourceLength); regionStart=\(offset); regionLength=\(count)")
  }


}
