/*
 *This is generated by J2Swift, donot modify 
 */


import Foundation

public class JavaTypeNotPresentException : JavaRuntimeException {

  private static let serialVersionUID:jlong = -5101214195716534496

  private var typeName_:String?

  public override init(withString typeName:String?, withJavaThrowable cause:JavaThrowable?)  {
    
    super.init(withString: "Type \(typeName) not present",withJavaThrowable: cause)
    self.typeName_ = typeName
  }

  public func typeName() ->String?  {
    return typeName_
  }


}
